[package]
name = "bitmap-crdt"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = { version = "1.10.1", features = ["serde"] }
roaring = { version = "0.11.2", features = ["serde"] }
serde = { version = "1.0.226", features = ["derive"] }
thiserror = "2.0.16"
